//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formacio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefonos
    {
        public int id { get; set; }
        public string codigo { get; set; }
        public string imageURL { get; set; }
        public string name { get; set; }
        public string snippet { get; set; }
        public string additionalFeatures { get; set; }
        public int idSo { get; set; }
    
        public virtual So So { get; set; }
    }
}
